<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-R6TPNCRO" failures="1" tests="5" name="Test" time="59.844" errors="0" timestamp="2025-06-30T23:46:37 IST">
  <testcase classname="testCases.TC003_Login_DDT" name="verify_loginDDT" time="6.949"/>
  <testcase classname="testCases.TC003_Login_DDT" name="verify_loginDDT" time="4.788"/>
  <testcase classname="testCases.TC003_Login_DDT" name="verify_loginDDT" time="7.299">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_Login_DDT.verify_loginDDT(TC003_Login_DDT.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC003_Login_DDT" name="verify_loginDDT" time="15.96"/>
  <testcase classname="testCases.TC003_Login_DDT" name="verify_loginDDT" time="5.134"/>
</testsuite> <!-- Test -->
